### ISSUE TITLE
请求改善一下语法

### ISSUE THREAD

**Issue by ft9765581** [txs1992/stylus-converter#111]
因为要转换的CSS文件还是挺多的，现在单个转换还是挺累的，能否增加一件转换文件夹功能，或者参考ES6的解构赋值的命名方式，比如我想转换icon文件格式，但是不改变名字，可以简写成stylus-conver -i icon.styl -o

**Comment by txs1992** [comment]
@ft9765581 

![image](https://user-images.githubusercontent.com/17583395/122339337-89802f00-cf73-11eb-8f8c-811c2e3af5db.png)

这个是替换文件夹的 demo

![image](https://user-images.githubusercontent.com/17583395/122339448-b16f9280-cf73-11eb-8b80-e83fe84b0770.png)
