### ISSUE TITLE
Loses single-line comments in source files

### ISSUE THREAD

**Issue by turadg** [txs1992/stylus-converter#55]
[Stylus supports single-line comments](http://stylus-lang.com/docs/comments.html#single-line), but they're lost in conversion.

E..g,
```
div {
  // http://stylus-lang.com/docs/comments.html#single-line
  margin 0  // http://stylus-lang.com/docs/comments.html#single-line
}
```
-->
```
div  {

  margin: 0;
}
```

**Comment by txs1992** [comment]
@turadg HI~

**Comment by txs1992** [comment]
@turadg Thank you for your question. I need to look at it.

**Comment by txs1992** [comment]
@turadg My tool is based on stylus parser parsed ast object, stylus seems to abandon the handling of single-line comments when converting ast, so I have no way to handle single-line comments.

**Comment by txs1992** [comment]
@turadg I added a new attribute to the stylus converter version 0.5.1. If you want to keep comments, just add -s yes in cli. I will change the single-line comment in the file to a multiline comment.
